name: Documentation edit
description: Documentation changes for Toolkit
labels: ["type: documentation", "etc: triage"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Basic checklist
      options:
        - label: I have searched existing issues and did not find a duplicate of my issue
          required: false
        - label: I am aware that shaders and other intensive overhauls will not be added
          required: false
        - label: I am aware that OptiFine will not be added
          required: false
        - label: I have not been truthful to the above boxes
          required: false
  - type: dropdown
    id: game
    attributes:
      label: Documentation for...
      description: What needs documentation?
      options:
        - Minecraft
        - WEBFISHING
        - Placeholder wiki
        - General documentation
      default: 0
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Explain what needs to be added, removed or changed
      placeholder: Add details
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add extra context that could be important. Include any incompatibilities or other important issues.
      placeholder: Add details
    validations:
      required: false
